### ISSUE TITLE
runs ok, but doesn't let me...

### ISSUE THREAD

**Issue by kanliot** [nebulaw2081d/nebula_draw#1]
I wanted a quick drawing software that would let me type.  
I don't see how to type in this thing.  It compiles fine on linux though.

also, I'd like to use the arrow keys as well, (with a visible cursor)

cheers!

**Comment by nebulaw2081d** [comment]
@kanliot I can add this in, but I am not sure what the advantage would be. Using any standard text editor would be able to accomplish such functionality, as well as being able to export said drawing into a file. Currently, there is no stable functionality for that in Nebula Draw.

**Comment by nebulaw2081d** [comment]
@kanliot I have been thinking about #1 for a while now and it has led me to think about this project. I started it because I thought a terminal based drawing application was a niche that had not been filled and wanted to learn the ncurses library. Although, in retrospective I see it had not been done before as a terminal is not a good interface for such a graphical based thing, especially when using the mouse. ncurses was never built for such an application and I realize that now. After compiling it today and running it in my terminal, I see how many bugs it has and how much more work is required for it to even be near considered usable. I doubt even if I spent twice as much time as I did on it, it would reach a stage in its development where it would be useable.

I have been experimenting with creating an X11 port of this project, but I have found it would be in a position where it could not compete with the likes of GIMP and would be useless as an ASCII drawing program due to the lack of a text-based interface such as a terminal. 

I'll be archiving this repository soon to indicate this project will not be receiving updates and is to be considered abandoned. I am sorry my application was unable to meet your needs, as The Nebula Centre Project and I love software that is useful and serves a purpose.
